#!/usr/bin/env python3
"""
SUMO Network Generation Script
Generates a clean 4-way intersection with proper geometry using netconvert.
"""

import os
import subprocess
import sys
from pathlib import Path

# Get the directory where this script is located
SCRIPT_DIR = Path(__file__).parent.absolute()


def create_node_file():
    """Create the node XML file defining junction and boundary nodes."""
    nodes_xml = """<?xml version="1.0" encoding="UTF-8"?>
<nodes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/nodes_file.xsd">
    <!-- Central traffic light controlled junction -->
    <node id="TL" type="traffic_light" x="500.0" y="500.0" />
    
    <!-- Boundary nodes (dead ends) -->
    <node id="N" type="dead_end" x="500.0" y="0.0" />
    <node id="S" type="dead_end" x="500.0" y="1000.0" />
    <node id="E" type="dead_end" x="1000.0" y="500.0" />
    <node id="W" type="dead_end" x="0.0" y="500.0" />
</nodes>
"""
    
    node_file = SCRIPT_DIR / "intersection.nod.xml"
    with open(node_file, 'w') as f:
        f.write(nodes_xml)
    print(f"✓ Created {node_file}")
    return node_file


def create_edge_file():
    """Create the edge XML file defining roads between nodes."""
    edges_xml = """<?xml version="1.0" encoding="UTF-8"?>
<edges xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/edges_file.xsd">
    <!-- Incoming edges to the traffic light -->
    <edge id="N2TL" from="N" to="TL" priority="2" numLanes="1" speed="13.89" />
    <edge id="S2TL" from="S" to="TL" priority="2" numLanes="1" speed="13.89" />
    <edge id="E2TL" from="E" to="TL" priority="2" numLanes="1" speed="13.89" />
    <edge id="W2TL" from="W" to="TL" priority="2" numLanes="1" speed="13.89" />
    
    <!-- Outgoing edges from the traffic light -->
    <edge id="TL2N" from="TL" to="N" priority="2" numLanes="1" speed="13.89" />
    <edge id="TL2S" from="TL" to="S" priority="2" numLanes="1" speed="13.89" />
    <edge id="TL2E" from="TL" to="E" priority="2" numLanes="1" speed="13.89" />
    <edge id="TL2W" from="TL" to="W" priority="2" numLanes="1" speed="13.89" />
</edges>
"""
    
    edge_file = SCRIPT_DIR / "intersection.edg.xml"
    with open(edge_file, 'w') as f:
        f.write(edges_xml)
    print(f"✓ Created {edge_file}")
    return edge_file


def generate_network(node_file, edge_file):
    """Use netconvert to generate the network file."""
    output_file = SCRIPT_DIR / "network.net.xml"
    
    # Build netconvert command
    cmd = [
        "netconvert",
        "--node-files", str(node_file),
        "--edge-files", str(edge_file),
        "--output-file", str(output_file),
        "--no-turnarounds", "true",
        "--junctions.corner-detail", "5",
        "--junctions.limit-turn-speed", "5.5",
        "--default.lanewidth", "3.2",
        "--default.junctions.radius", "4",
        "--tls.default-type", "static",
    ]
    
    print(f"\n🔧 Running netconvert...")
    print(f"Command: {' '.join(cmd)}\n")
    
    try:
        result = subprocess.run(
            cmd,
            cwd=str(SCRIPT_DIR),
            capture_output=True,
            text=True,
            check=True
        )
        
        print("✓ Network generation successful!")
        print(f"✓ Created {output_file}")
        
        if result.stdout:
            print(f"\nnetconvert output:\n{result.stdout}")
        
        return output_file
        
    except subprocess.CalledProcessError as e:
        print(f"❌ Error running netconvert:")
        print(f"Return code: {e.returncode}")
        print(f"STDOUT: {e.stdout}")
        print(f"STDERR: {e.stderr}")
        sys.exit(1)
    except FileNotFoundError:
        print("❌ Error: netconvert not found in PATH")
        print("Please ensure SUMO is installed and netconvert is in your PATH")
        sys.exit(1)



def backup_old_network():
    """Backup the old network file if it exists."""
    old_network = SCRIPT_DIR / "network.net.xml"
    if old_network.exists():
        backup_file = SCRIPT_DIR / "network.net.xml.backup"
        import shutil
        shutil.copy2(old_network, backup_file)
        print(f"✓ Backed up old network to {backup_file}")


def main():
    """Main function to generate the SUMO network."""
    print("=" * 60)
    print("SUMO Network Generator")
    print("Generating clean 4-way intersection with proper geometry")
    print("=" * 60)
    print()
    
    # Backup old network
    backup_old_network()
    
    # Create XML files
    node_file = create_node_file()
    edge_file = create_edge_file()
    
    # Generate network (connections will be auto-generated by netconvert)
    network_file = generate_network(node_file, edge_file)
    
    print("\n" + "=" * 60)
    print("✅ Network generation complete!")
    print("=" * 60)
    print(f"\nGenerated files:")
    print(f"  - {node_file}")
    print(f"  - {edge_file}")
    print(f"  - {network_file}")
    print(f"\nYou can now run your simulation with the new network.")
    print(f"To visualize: sumo-gui -c {SCRIPT_DIR / 'simulation.sumocfg'}")



if __name__ == "__main__":
    main()
